import json
import os


def get_cookies_path():
    from config import INSTAGRAM_COOKIES_JSON

    return INSTAGRAM_COOKIES_JSON


def load_cookies_json() -> list:
    """Load Instagram cookies from JSON file."""
    cookies_path = get_cookies_path()
    if not os.path.exists(cookies_path):
        return []
    try:
        with open(cookies_path, "r") as f:
            data = json.load(f)
            if isinstance(data, list):
                return data
            elif isinstance(data, dict) and "cookies" in data:
                return data["cookies"]
            return []
    except (json.JSONDecodeError, IOError):
        return []


def validate_cookies(cookies: list) -> bool:
    """Validate cookie structure."""
    if not isinstance(cookies, list):
        return False
    for cookie in cookies:
        if not isinstance(cookie, dict):
            return False
        if "name" not in cookie or "value" not in cookie:
            return False
    return len(cookies) > 0


def cookies_to_netscape(cookies: list) -> str:
    """Convert JSON cookies to Netscape format for yt-dlp."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by Videos Victor",
    ]
    for cookie in cookies:
        domain = cookie.get("domain", ".instagram.com")
        flag = "TRUE"
        path = cookie.get("path", "/")
        secure = cookie.get("secure", "TRUE")
        expiration = str(cookie.get("expires", "0"))
        name = cookie.get("name", "")
        value = cookie.get("value", "")
        lines.append(
            f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}"
        )
    return "\n".join(lines)


def save_cookies_for_ytdlp(cookies: list, output_path: str = None) -> str:
    """Save cookies in Netscape format to temp file for yt-dlp."""
    from config import DOWNLOADS_DIR

    if output_path is None:
        output_path = os.path.join(DOWNLOADS_DIR, "instagram_cookies.txt")
    netscape_content = cookies_to_netscape(cookies)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(netscape_content)
    return output_path


def save_cookies(cookies: list) -> bool:
    """Save cookies from user input to JSON file."""
    cookies_path = get_cookies_path()
    try:
        with open(cookies_path, "w", encoding="utf-8") as f:
            json.dump(cookies, f, indent=2)
        return True
    except IOError:
        return False


def get_cookies_status() -> dict:
    """Check if cookies are configured and valid."""
    cookies = load_cookies_json()
    if not cookies:
        return {
            "configured": False,
            "valid": False,
            "message": "No hay cookies configuradas",
        }
    if validate_cookies(cookies):
        return {
            "configured": True,
            "valid": True,
            "message": "Cookies configuradas correctamente",
        }
    return {"configured": True, "valid": False, "message": "Cookies inválidas"}
